document.addEventListener('DOMContentLoaded', function() {
    const moodForm = document.getElementById('moodForm');
  
    moodForm.addEventListener('submit', function(event) {
      event.preventDefault(); // Prevent the form from submitting the traditional way
      const selectedMood = document.getElementById('moodDropdown').value;
      generatePlaylistForMood(selectedMood);
    });
  });
  
  function generatePlaylistForMood(mood) {
    const attributes = mapMoodToAttributes(mood);
    fetchTracksWithAttributes(attributes).then(tracks => {
      if (tracks.length > 0) {
        createOrUpdatePlaylist(tracks);
      } else {
        alert('No tracks found for this mood. Please try a different mood.');
      }
    }).catch(error => {
      console.error('Error fetching tracks:', error);
      alert('An error occurred while generating the playlist.');
    });
  }
  
  function mapMoodToAttributes(mood) {
    // Replace with actual logic based on Spotify's API
    return {
      valence: mood === 'happy' ? 0.8 : mood === 'sad' ? 0.2 : 0.5,
      energy: mood === 'energetic' ? 0.8 : 0.4,
      // Add other attributes if needed
    };
  }
  
  function fetchTracksWithAttributes(attributes) {
    // Replace with actual Spotify API call
    return fetch(`https://api.spotify.com/v1/recommendations?seed_genres=pop&target_valence=${attributes.valence}&target_energy=${attributes.energy}`, {
      headers: {
        'Authorization': `Bearer ${access_token}` // Using access_token from spot.js
      }
    })
    .then(response => response.json())
    .then(data => {
      // Extracting track URIs from the response
      return data.tracks.map(track => track.uri);
    });
  }
  
  function createOrUpdatePlaylist(tracks) {
    // Replace with actual Spotify API call for playlist creation/updating
    const userId = 'YOUR_SPOTIFY_USER_ID'; // Replace with actual user ID
  
    // Create a new playlist
    return fetch(`https://api.spotify.com/v1/users/${userId}/playlists`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${access_token}`, // Using access_token from spot.js
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: `Mood Playlist: ${new Date().toLocaleDateString()}`, // Playlist name with current date
        description: 'Generated by TuneSculpt',
        public: false
      })
    })
    .then(response => response.json())
    .then(playlist => {
      // Add tracks to the newly created playlist
      return fetch(`https://api.spotify.com/v1/playlists/${playlist.id}/tracks`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${access_token}`, // Using access_token from spot.js
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ uris: tracks })
      });
    })
    .then(() => {
      alert('Playlist generated successfully!');
    })
    .catch(error => {
      console.error('Error creating or updating playlist:', error);
      alert('An error occurred while creating the playlist.');
    });
  }
  